name: Blob storage website CI

on: [workflow_dispatch]


env:
  STORAGE_ACCOUNT_NAME: "terraformaccount202310"
  SOURCE_PATH: "./public/"
  CDN_PROFILE_NAME: "MyFrontDoor"
  CDN_ENDPOINT: "afd-742c2b4ffcf1d3a1"
  RESOURCE_GROUP: "terraform-beginner-bootcamp-2023-azure"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --overwrite --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --auth-mode key -d '$web' -s ${{ env.SOURCE_PATH }}
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az afd endpoint purge --content-paths  "/*" --profile-name ${{ env.CDN_PROFILE_NAME }} --endpoint-name ${{ env.CDN_ENDPOINT }} --resource-group ${{ env.RESOURCE_GROUP }}
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
